// Mocks generated by Mockito 5.0.17 from annotations
// in flutter_bloc_test_nextbase/test/home_page/video_charts_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:flutter_bloc_test_nextbase/core/services/sample_data.dart'
    as _i2;
import 'package:flutter_bloc_test_nextbase/data_layer/data_models/video_meta_data_model.dart'
    as _i3;
import 'package:flutter_bloc_test_nextbase/data_layer/respository/video_meta_repo.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeMobileService_0 extends _i1.Fake implements _i2.MobileService {}

class _FakeVideoMetaDataModel_1 extends _i1.Fake
    implements _i3.VideoMetaDataModel {}

/// A class which mocks [VideoMetaDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoMetaDataRepository extends _i1.Mock
    implements _i4.VideoMetaDataRepository {
  MockVideoMetaDataRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MobileService get remoteService =>
      (super.noSuchMethod(Invocation.getter(#remoteService),
          returnValue: _FakeMobileService_0()) as _i2.MobileService);
  @override
  set remoteService(_i2.MobileService? _remoteService) =>
      super.noSuchMethod(Invocation.setter(#remoteService, _remoteService),
          returnValueForMissingStub: null);
  @override
  _i5.Future<_i3.VideoMetaDataModel> getVideoMetaDataModel() =>
      (super.noSuchMethod(Invocation.method(#getVideoMetaDataModel, []),
              returnValue: Future<_i3.VideoMetaDataModel>.value(
                  _FakeVideoMetaDataModel_1()))
          as _i5.Future<_i3.VideoMetaDataModel>);
}
